[project]
name = "nlp"
version = "0.1.0"
description = ""
authors = [{ name = "lwtztea", email = "luneva.na@phystech.edu" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bokeh>=3.8.0",
    "gensim>=4.3.3",
    "matplotlib>=3.10.7",
    "nltk>=3.9.2",
    "numpy<2.0",
    "scipy<1.14",
    "umap>=0.1.1",
    "umap-learn>=0.5.9.post2",
]
